name: Caliper Benchmarks
version: "2.0.0"
# mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.1.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB
 
channels:
  - channelName: mychannel
    # the chaincodeIDs of all the fabric chaincodes in caliper-benchmarks
    contracts:
    - id: chaincode1

organizations:
  - mspid: Org1MSP
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
        clientSignedCert:
          path: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
    connectionProfile:
      path: crypto-config/peerOrganizations/org1.example.com/connection-org1.json
      discover: true
